### ISSUE TITLE
error while compiling on fedora 27!

### ISSUE THREAD

**Issue by amarts** [gluster/glusterfs-posix2#1]
Not sure what is wrong, all the dependencies are installed, and I did this:

```
# make dist
# rpmbuild -ta glusterfs-posix2-6dev.tar.gz
```

and below is the error I get!

```
make[6]: Entering directory '/home/atumball/rpmbuild/BUILD/glusterfs-posix2-6dev/xlators/experimental/posix2/common/src'
/bin/sh ../../../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../../..  -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DGF_LINUX_HOST_OS  -Wall -I /usr/include/glusterfs -I /usr/include/glusterfs/rpc -I /usr/include/glusterfs/xdr -isystem /usr/include/tirpc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -c -o libposix2common_la-posix2-common.lo `test -f 'posix2-common.c' || echo './'`posix2-common.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../../.. -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DGF_LINUX_HOST_OS -Wall -I /usr/include/glusterfs -I /usr/include/glusterfs/rpc -I /usr/include/glusterfs/xdr -isystem /usr/include/tirpc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -c posix2-common.c  -fPIC -DPIC -o .libs/libposix2common_la-posix2-common.o
In file included from /usr/include/glusterfs/glusterfs.h:54:0,
                 from posix2-common.c:16:
/usr/include/glusterfs/atomic.h:94:25: error: expected specifier-qualifier-list before 'GF_ATOMIC_SIZE_SIZEOF_LONG'
         GF_ATOMIC_MACRO(GF_ATOMIC_SIZE_, _size);                               \
                         ^
/usr/include/glusterfs/atomic.h:20:35: note: in definition of macro 'GF_ATOMIC_MACRO_1'
 #define GF_ATOMIC_MACRO_1(_macro) _macro
                                   ^~~~~~
/usr/include/glusterfs/atomic.h:94:9: note: in expansion of macro 'GF_ATOMIC_MACRO'
         GF_ATOMIC_MACRO(GF_ATOMIC_SIZE_, _size);                               \
         ^~~~~~~~~~~~~~~
/usr/include/glusterfs/atomic.h:103:1: note: in expansion of macro 'GF_ATOMIC_TYPE'
 GF_ATOMIC_TYPE(SIZEOF_LONG, intptr);  /* gf_atomic_intptr_t */
 ^~~~~~~~~~~~~~
/usr/include/glusterfs/atomic.h:94:25: error: expected specifier-qualifier-list before 'GF_ATOMIC_SIZE_SIZEOF_LONG'
         GF_ATOMIC_MACRO(GF_ATOMIC_SIZE_, _size);                               \
                         ^
/usr/include/glusterfs/atomic.h:20:35: note: in definition of macro 'GF_ATOMIC_MACRO_1'
 #define GF_ATOMIC_MACRO_1(_macro) _macro
                                   ^~~~~~
/usr/include/glusterfs/atomic.h:94:9: note: in expansion of macro 'GF_ATOMIC_MACRO'
         GF_ATOMIC_MACRO(GF_ATOMIC_SIZE_, _size);                               \
         ^~~~~~~~~~~~~~~
/usr/include/glusterfs/atomic.h:108:1: note: in expansion of macro 'GF_ATOMIC_TYPE'
 GF_ATOMIC_TYPE(SIZEOF_LONG, uintptr); /* gf_atomic_uintptr_t */
 ^~~~~~~~~~~~~~
In file included from /usr/include/glusterfs/inode.h:32:0,
                 from /usr/include/glusterfs/statedump.h:15,
                 from posix2-common.c:18:
/usr/include/glusterfs/iatt.h:69:5: error: unknown type name 'uuid_t'
     uuid_t ia_gfid;
     ^~~~~~
/usr/include/glusterfs/iatt.h:76:5: error: unknown type name 'uuid_t'
     uuid_t ia_gfid;
     ^~~~~~
/usr/include/glusterfs/iatt.h: In function 'oldiatt_from_iatt':
/usr/include/glusterfs/iatt.h:412:5: warning: implicit declaration of function 'gf_uuid_copy'; did you mean 'gf_cmd_log'? [-Wimplicit-function-declaration]
     gf_uuid_copy(o_iatt->ia_gfid, c_iatt->ia_gfid);
     ^~~~~~~~~~~~
     gf_cmd_log
In file included from /usr/include/glusterfs/fd-lk.h:21:0,
                 from /usr/include/glusterfs/fd.h:19,
                 from /usr/include/glusterfs/inode.h:34,
                 from /usr/include/glusterfs/statedump.h:15,
                 from posix2-common.c:18:
/usr/include/glusterfs/common-utils.h: At top level:
/usr/include/glusterfs/common-utils.h:46:10: fatal error: uuid.h: No such file or directory
 #include "uuid.h"
          ^~~~~~~~
compilation terminated.
make[6]: *** [Makefile:450: libposix2common_la-posix2-common.lo] Error 1
make[6]: Leaving directory '/home/atumball/rpmbuild/BUILD/glusterfs-posix2-6dev/xlators/experimental/posix2/common/src'
```

**Comment by kalebskeithley** [comment]
are you sure you have libuuid-devel installed?  Is  there a /usr/lib64/pkgconfig/uuid.pc? /usr/include/uuid/uuid.h? (And /me tries to remember how to fix the GF_ATOMIC_SIZE thing)

**Comment by kalebskeithley** [comment]
glusterfs 6dev actually installed? Is there a /usr/lib64/pkgconfig/glusterfs-api.pc installed?

**Comment by kalebskeithley** [comment]
is glusterfs 6dev actually installed? From rpms or `make install` ?

**Comment by kalebskeithley** [comment]
never mind. It's an issue with master (and maybe the release-5) branch that came in when .../contrib/uuid was removed

Core gluster compiles with -I/usr/include/uuid, but it wasn't added to the glusterfs-api.pc file in glusterfs-api-devel.

It works with 4.1.x though, try using that until master gets fixed.

**Comment by kalebskeithley** [comment]
master and release-5 branch need https://review.gluster.org/c/glusterfs/+/21420
with that and the latest push it should work for you too.
